#!/bin/bash

if [[ $GIT_DIR == "" ]]; then
echo Hook script. You should not invoke it directly!
exit 1
fi
 
PREV_COMMIT=`git rev-parse "HEAD@{1}"`
POST_COMMIT=`git rev-parse "HEAD@{0}"`

HOOXSOURCE="source/"

echo "$0 invoked. Previous commit: ${PREV_COMMIT}. Actual commit: ${POST_COMMIT}"
 
DIFF=`git diff --name-only $PREV_COMMIT..$POST_COMMIT $HOOXSOURCE`

if [[ $DIFF != "" ]]; then

	echo "$HOOXSOURCE has changed. Applying fixlinks..."

	if [ -f dev-tools/fixlinks.bat ]; then

		cmd.exe /c dev-tools\\fixlinks.bat
		
	else
	
		echo Could not locate fixlinks.bat. Aborting.
		exit 1
		
	fi

else

	echo Checkout did not affect files in $HOOXSOURCE

fi

echo Done.

exit 0
